name: Go
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23.x', '1.24.x', '1.25.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go get .

      - name: Test project
        run: |
          go test -v -race ./...

      - name: Build
        run: go build -v ./...
